# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write 
  actions: read

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # PUBLISH
  ###################################################

  build:
    name: Publish NuGet Packages
    if: "!contains(github.event.head_commit.message, 'skip-ci') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Show tag & MinVer
        run: |
          git describe --tags --always --dirty

      - name: Publish
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake --target="publish" --configuration="Release" \
            --nuget-key="${{secrets.NUGET_API_KEY}}" \
            --github-key="${{secrets.GITHUB_TOKEN}}"

